In [ ]:
import numpy as np


In [ ]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [ ]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [ ]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [ ]:
price_per_unit*units # broadcasting

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [ ]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [ ]:
revenues_usd = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenues_inr = 75*revenues_usd # converting USD to INR
revenues_inr

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [ ]:
units_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit = np.array([20,30,15])

In [ ]:
total_sales_amount = np.dot(price_per_unit,units_sold)
total_sales_amount

array([1900, 2640, 1430])

# **loss and cost function**

**loss functions types**
- Mean Absolute Error=1/n summation abs(y-y^)
- Mean Square Error= 1/n summation (y-y^)^2
- Log loss(or)Binary Cross Entropy= 1/n summation ylog(y^)+(1-y).log(1-y^)

Note:
- Individual errors are called loss
- Cummulative error is called cost function

In [ ]:
import numpy as np

**Mean Absolute Error**

In [ ]:
y_pred=np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [ ]:
def mae(y_true,y_pred):
    total_error=0
    for yt,yp in zip(y_true,y_pred):
        total_error+=abs(yt-yp)
    print("Total error:",total_error)
    mae=total_error/len(y_true)
    print("Mean absolute error:",mae)
    return mae

In [ ]:
mae(y_true,y_pred)

Total error: 2.5
Mean absolute error: 0.5


0.5

In [ ]:
np.mean(np.abs(y_pred-y_true))#mean absolute error

0.5

In [ ]:
np.sum(np.abs(y_pred-y_true))# total error

2.5

**Log Loss (or) Binary Cross Entropy**

In [ ]:
np.log([0.000000000000000001])

array([-41.44653167])

In [ ]:
epslion = 1e-15

In [ ]:
y_pred_new = [max(i,epslion) for i in y_pred]
y_pred_new

[1, 1, 1e-15, 1e-15, 1]

In [ ]:
y_pred_new = [min(i,1-epslion) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [ ]:
y_pred_new = np.array(y_pred_new)
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [ ]:
-np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

17.2696280766844

In [ ]:
def log_loss(y_true,y_pred):
    epslion = 1e-15
    y_pred_new = [max(i,epslion) for i in y_pred]
    y_pred_new = [min(i,1-epslion) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [ ]:
log_loss(y_true,y_pred)

17.2696280766844

**Mean Square Error**

In [ ]:
def mse(y_true,y_pred):
    total_error=0
    for yt,yp in zip(y_true,y_pred):
        total_error+=(yt-yp)**2
    print("Total error:",total_error)
    mse=total_error/len(y_true)
    print("Mean square error:",mse)
    return mse

**without using numpy**

In [ ]:
mse(y_true,y_pred)

Total error: 1.83
Mean square error: 0.366


0.366

**with using numpy**

In [ ]:
np.mean(np.square(y_pred-y_true))#mean square error

0.366

In [ ]:
np.sum(np.square(y_pred-y_true))# total error

1.83